stages:
  - id: spec-generate
    name: 需求澄清与编码方案设计
    confirm: true
    node:
      ref: spec
      type: builtin
  - id: spec-coding
    name: 编码实现
    node:
      ref: spec-coding
      type: builtin   
  - id: local-test
    name: 本地测试
    node:
      ref: local-test
      type: builtin
  - id: aone-ci
    name: aone-ci-test
    node:
      ref: aone-ci
      type: custom
  - id: spec-archive
    name: 需求归档
    node:
      ref: spec-archive
      type: custom 
  - id: code-review
    name: 代码评审
    node:
      ref: code-review
      type: builtin
