package models

// TrustCard represents a trusted agent card generated by CNNIC during registration.
type TrustCard struct {
	AgentID          string              `json:"agentId"`
	AgentName        string              `json:"agentName"`
	AgentDisplayName string              `json:"agentDisplayName"`
	AgentDescription string              `json:"agentDescription"`
	Version          string              `json:"version"`
	AgentHost        string              `json:"agentHost"`
	Endpoints        []TrustCardEndpoint `json:"endpoints"`
	SecuritySchemes  map[string]any      `json:"securitySchemes,omitempty"`
	VerifiableClaims []map[string]any    `json:"verifiableClaims,omitempty"`
}

// TrustCardEndpoint describes a protocol endpoint for an agent.
type TrustCardEndpoint struct {
	Protocol    string             `json:"protocol"`
	AgentURL    string             `json:"agentUrl"`
	MetadataURL string             `json:"metadataUrl,omitempty"`
	DocURL      string             `json:"docUrl,omitempty"`
	Transports  []string           `json:"transports,omitempty"`
	Functions   []EndpointFunction `json:"functions,omitempty"`
}

// EndpointFunction describes a function exposed by an agent endpoint.
type EndpointFunction struct {
	ID   string   `json:"id"`
	Name string   `json:"name"`
	Tags []string `json:"tags,omitempty"`
}
